export default {
  preset: "impact",
  brand: {
    name: "Brejas & Birras PUB e SHOP",
    shortName: "BB",
    tagline: "Cervejas especiais, presentes e bons encontros em Araucária.",
    logo: "/assets/brejas-birras-logo.png",
    logoAlt: "Brejas & Birras",
  },
  seo: {
    title: "Brejas & Birras | Cervejas especiais em Araucária",
    description: "Brejas & Birras em Araucária: cervejas artesanais, growlers, vinhos, destilados, presentes e um pub para brindar com quem importa.",
    keywords: ["cervejas artesanais em Araucária", "pub em Araucária", "growler em Araucária", "presentes com cerveja em Araucária", "vinhos e destilados em Araucária", "Brejas & Birras"],
    canonical: "https://brejas-birras-lp.vercel.app/",
    locale: "pt_BR",
    schemaType: "BarOrPub",
  },
  announcement: { label: "Araucária · Terça a domingo · 11h às 00h", actionLabel: "Pedir agora" },
  contact: {
    primaryLabel: "Pedir agora",
    footerPrimaryLabel: "Pedir agora",
    primaryUrl: "https://pedido.anota.ai/login/?access_token=eyJhbGciOiJIUzI1NiJ9.eyJpZGNsaWVudCI6IjY5ZjNlNDg1MmY0NGRjZjQxNmVjM2RlZSIsImlkcGFnZSI6IjY5YjliNGM4ZWU3YmQ5MWJjMjgzZjc4NCIsImxpbmtfYWNjZXNzZWQiOmZhbHNlLCJ3aGF0c2FwcCI6dHJ1ZX0.fGM8Jp0RMWo7LnwDG0SJ9zQfY79Z0t3QcSk6dM-62BA&from=whats&f=ms",
    secondaryAction: {
      label: "Reservar uma mesa",
      url: "https://wa.me/message/T6NJPWCFOY3OC1",
    },
    phone: "+554137972385",
    instagramLabel: "Loja e presentes",
    socialLabel: "Loja e presentes",
    instagramUrl: "https://www.instagram.com/brejasebirras/",
    socialLinks: [
      { label: "Loja e presentes", url: "https://www.instagram.com/brejasebirras/" },
      { label: "Instagram do pub", url: "https://www.instagram.com/brejasebirraspub/" },
    ],
    mapsUrl: "https://maps.app.goo.gl/NCXdH7xg3omd8mWB9",
  },
  navigation: [
    { label: "O que tem", href: "#servicos" },
    { label: "Avaliações", href: "#avaliacoes" },
    { label: "Como chegar", href: "#visite" },
  ],
  hero: {
    kicker: "LOJA · PUB · PRESENTES",
    title: ["Brinde", "do seu", "jeito."],
    accentLine: 1,
    description: "Uma loja de cervejas e presentes. Um pub de pratos, drinks e chopes para aproveitar sem pressa.",
    image: "/assets/brejas-hero.jpg",
    imageAlt: "Cerveja especial apresentada no Brejas & Birras",
    imagePosition: "60% center",
    proofLabel: "4,6 no Google",
    proofValue: "306 avaliações",
    scrollLabel: "Conheça o Brejas",
  },
  statement: {
    label: "O seu ponto de brinde em Araucária",
    text: "Para levar. Para ficar.",
    accent: "Para ficar.",
  },
  services: {
    title: "Loja para escolher. Pub para ficar.",
    description: "Duas experiências que se encontram no mesmo endereço: um presente bem escolhido ou uma noite para reunir quem importa.",
    items: [
      { title: "Loja para descobrir", description: "Cervejas artesanais, growlers, vinhos, destilados e novidades no freezer para levar ou presentear.", detail: "Cervejas · growlers · presentes" },
      { title: "Pub para aproveitar", description: "Pratos à la carte, baguetes, porções, chopes artesanais e drinks para transformar a mesa no programa.", detail: "Comida · chopes · drinks" },
      { title: "Presentes que têm história", description: "Kits e combinações para criar um presente com a cara de quem vai receber.", detail: "Kits prontos · escolhas personalizadas" },
    ],
  },
  gallery: {
    label: "Tem sempre algo novo no Brejas",
    title: "Da cerveja que chegou hoje ao presente que você ainda não imaginou.",
    items: [
      { image: "/assets/brejas-novidades.jpg", alt: "Novidades de cervejas especiais no Brejas & Birras", caption: "Novidades para provar" },
      { image: "/assets/brejas-brinde.jpg", alt: "Pessoas brindando no Brejas & Birras", caption: "Motivos para reunir" },
      { image: "/assets/brejas-presentes.jpg", alt: "Sacola de presente do Brejas & Birras", caption: "Presentes para levar" },
    ],
  },
  reviews: {
    label: "Avaliações no Google",
    title: "Quem vem, quer voltar para brindar de novo.",
    rating: "4,6",
    total: "306 avaliações no Google",
    sourceLabel: "Ver avaliações no Google Maps",
    items: [
      { quote: "Não importa qual seja sua escolha, todo cardápio do Brejas é ótimo. As bebidas também são ótimas — melhor pub de Araucária com toda certeza.", author: "Mario Kmiecik Drummer", score: "5/5 no Google" },
      { quote: "Ambiente top, vou sempre com amigos e família. Tem ótima comida e bebida.", author: "Cliente do Google", score: "5/5 no Google" },
      { quote: "Ótimo lugar, um dos melhores lugares para tomar um bom chopp na cidade!", author: "Cliente do Google", score: "5/5 no Google" },
    ],
  },
  location: {
    label: "Venha brindar com a gente",
    title: "No centro de Araucária, perto do seu próximo encontro.",
    description: "Passe para escolher uma cerveja, montar um presente ou ficar para aproveitar o pub. Estamos na Av. Archelau de Almeida Tôrres.",
    actionLabel: "Abrir no Google Maps",
    addressLines: ["Av. Archelau de Almeida Tôrres, 119", "Centro · Araucária — PR"],
    address: { street: "Av. Archelau de Almeida Tôrres, 119", city: "Araucária", region: "PR", postalCode: "83702-185", country: "BR" },
    hours: ["Terça a domingo · 11h às 00h", "Segunda · fechado", "Consulte o Instagram para novidades e eventos"],
    openingHours: [{ days: ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], opens: "11:00", closes: "00:00" }],
    mapEmbedUrl: "https://www.google.com/maps?q=Av.+Archelau+de+Almeida+T%C3%B4rres,+119,+Arauc%C3%A1ria,+PR&output=embed",
  },
  theme: {
    accent: "#f8c600",
    accentStrong: "#ffd94a",
    ink: "#101511",
    paper: "#f8f6ed",
    displayFont: "'Archivo Black', Arial Black, sans-serif",
    bodyFont: "'DM Sans', Arial, sans-serif",
  },
};
