export default {
  preset: "impact",
  brand: {
    name: "Brejas & Birras PUB e SHOP",
    shortName: "BB",
    tagline: "Cervejas especiais, presentes e bons encontros em Araucária.",
    logo: "/assets/brejas-birras-logo.png",
    logoAlt: "Brejas & Birras",
  },
  seo: {
    title: "Brejas & Birras | Cervejas especiais em Araucária",
    description: "Brejas & Birras em Araucária: cervejas artesanais, growlers, vinhos, destilados, presentes e um pub para brindar com quem importa.",
    keywords: ["cervejas artesanais em Araucária", "pub em Araucária", "growler em Araucária", "presentes com cerveja em Araucária", "vinhos e destilados em Araucária", "Brejas & Birras"],
    canonical: "https://brejas-birras-lp.vercel.app/",
    locale: "pt_BR",
    schemaType: "BarOrPub",
  },
  announcement: { label: "Araucária · Terça a domingo · 11h às 00h", actionLabel: "Ligar agora" },
  contact: {
    primaryLabel: "Ligar para a loja",
    footerPrimaryLabel: "Falar com o Brejas",
    primaryUrl: "tel:+554137972385",
    phone: "+554137972385",
    instagramLabel: "Ver Instagram",
    socialLabel: "Instagram",
    instagramUrl: "https://www.instagram.com/brejasebirras/",
    mapsUrl: "https://maps.app.goo.gl/NCXdH7xg3omd8mWB9",
  },
  navigation: [
    { label: "O que tem", href: "#servicos" },
    { label: "Avaliações", href: "#avaliacoes" },
    { label: "Como chegar", href: "#visite" },
  ],
  hero: {
    kicker: "PUB · SHOP · PRESENTES",
    title: ["Brinde", "do seu", "jeito."],
    accentLine: 1,
    description: "Brejas artesanais, growlers, vinhos, destilados e presentes para levar — ou uma mesa para ficar e aproveitar.",
    image: "/assets/brejas-hero.jpg",
    imageAlt: "Cerveja especial apresentada no Brejas & Birras",
    imagePosition: "60% center",
    proofLabel: "4,6 no Google",
    proofValue: "306 avaliações",
    scrollLabel: "Conheça o Brejas",
  },
  statement: {
    label: "O seu ponto de brinde em Araucária",
    text: "Aqui não tem só cerveja. Tem rótulo novo para descobrir, presente para acertar e aquela mesa que faz o encontro render mais uma rodada.",
    accent: "mais uma rodada.",
  },
  services: {
    title: "Chega, escolhe e brinda.",
    description: "Uma loja cheia de possibilidades e um pub pronto para receber — para a sua noite, seu presente ou a próxima descoberta cervejeira.",
    items: [
      { title: "Cervejas para descobrir", description: "Artesanais, nacionais, importadas e novidades no freezer para cada paladar e ocasião.", detail: "Latas · garrafas · estilos variados" },
      { title: "Growlers e outras escolhas", description: "Chopp para levar, vinhos, destilados e opções sem álcool para montar o seu próprio brinde.", detail: "Growlers · vinhos · destilados" },
      { title: "Presentes que têm história", description: "Kits e combinações para criar um presente com a cara de quem vai receber.", detail: "Kits prontos · escolhas personalizadas" },
    ],
  },
  gallery: {
    label: "Tem sempre algo novo no Brejas",
    title: "Do rótulo que chegou hoje ao presente que você ainda não imaginou.",
    items: [
      { image: "/assets/brejas-novidades.jpg", alt: "Novidades de cervejas especiais no Brejas & Birras", caption: "Novidades para provar" },
      { image: "/assets/brejas-brinde.jpg", alt: "Pessoas brindando no Brejas & Birras", caption: "Motivos para reunir" },
      { image: "/assets/brejas-presentes.jpg", alt: "Sacola de presente do Brejas & Birras", caption: "Presentes para levar" },
    ],
  },
  reviews: {
    label: "Avaliações no Google",
    title: "Quem vem, quer voltar para brindar de novo.",
    rating: "4,6",
    total: "306 avaliações no Google",
    sourceLabel: "Ver avaliações no Google Maps",
    items: [
      { quote: "Não importa qual seja sua escolha, todo cardápio do Brejas é ótimo. As bebidas também são ótimas — melhor pub de Araucária com toda certeza.", author: "Mario Kmiecik Drummer", score: "5/5 no Google" },
      { quote: "Ambiente top, vou sempre com amigos e família. Tem ótima comida e bebida.", author: "Cliente do Google", score: "5/5 no Google" },
      { quote: "Ótimo lugar, um dos melhores lugares para tomar um bom chopp na cidade!", author: "Cliente do Google", score: "5/5 no Google" },
    ],
  },
  location: {
    label: "Venha brindar com a gente",
    title: "No centro de Araucária, perto do seu próximo encontro.",
    description: "Passe para escolher um rótulo, montar um presente ou ficar para aproveitar o pub. Estamos na Av. Archelau de Almeida Tôrres.",
    actionLabel: "Abrir no Google Maps",
    addressLines: ["Av. Archelau de Almeida Tôrres, 119", "Centro · Araucária — PR"],
    address: { street: "Av. Archelau de Almeida Tôrres, 119", city: "Araucária", region: "PR", postalCode: "83702-185", country: "BR" },
    hours: ["Terça a domingo · 11h às 00h", "Segunda · fechado", "Consulte o Instagram para novidades e eventos"],
    openingHours: [{ days: ["Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"], opens: "11:00", closes: "00:00" }],
    mapEmbedUrl: "https://www.google.com/maps?q=Av.+Archelau+de+Almeida+T%C3%B4rres,+119,+Arauc%C3%A1ria,+PR&output=embed",
  },
  theme: {
    accent: "#f8c600",
    accentStrong: "#ffd94a",
    ink: "#101511",
    paper: "#f8f6ed",
    displayFont: "'Archivo Black', Arial Black, sans-serif",
    bodyFont: "'DM Sans', Arial, sans-serif",
  },
};
